version: '3'
services:
  app:
    build:
      context: ./php/
      dockerfile: Dockerfile
    image: laravel_app:latest
    container_name: app_container
    restart: unless-stopped
    tty: true
    working_dir: /var/www/
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: prod
    volumes:
      - ./php/app:/var/www/
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: laravel_db
    restart: always
    tty: true
    volumes:
      - data:/var/lib/postgresql/data
    links:
      - app
    env_file:
      - .configDB.env
  web:
    build:
      context: ./nginx/
    image: web_image
    container_name: web
    restart: always
    tty: true
    ports:
      - "8080:80"
      - "8081:443"


volumes:
  data:
    driver: local
networks:
  laravel-network:
    driver: bridge
